spring.application.name=proyectoseminario


spring.datasource.url=jdbc:postgresql://localhost:5432/SIPE
spring.datasource.username=postgres
spring.datasource.password=Aggtcraft1
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Thymeleaf Configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

# Server port
server.port=8080

# Logging
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG

# Spring AI Configuration
spring.ai.google.genai.api-key=${GOOGLE_GENAI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
