-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.evaluaciones
(
    id_evaluacion integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_paciente integer,
    id_instrumento integer,
    puntuacion character varying(10) COLLATE pg_catalog."default",
    nivel_riesgo character varying(50) COLLATE pg_catalog."default",
    fecha_aplicacion date,
    CONSTRAINT evaluaciones_pkey PRIMARY KEY (id_evaluacion)
    );

CREATE TABLE IF NOT EXISTS public.instrumentos
(
    id_instrumento integer NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default",
    descripcion character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT instrumentos_pkey PRIMARY KEY (id_instrumento)
    );

CREATE TABLE IF NOT EXISTS public.pacientes
(
    id_paciente integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(100) COLLATE pg_catalog."default",
    email character varying(50) COLLATE pg_catalog."default",
    fecha_nacimiento date,
    genero character varying(25) COLLATE pg_catalog."default",
    notas_clinicas character varying(255) COLLATE pg_catalog."default",
    estado_clinico character varying(25) COLLATE pg_catalog."default",
    fecha_registro date,
    id_usuario integer,
    CONSTRAINT pacientes_pkey PRIMARY KEY (id_paciente)
    );

CREATE TABLE IF NOT EXISTS public.preguntas
(
    id_pregunta serial NOT NULL,
    id_instrumento integer NOT NULL,
    enunciado text COLLATE pg_catalog."default" NOT NULL,
    orden integer NOT NULL,
    CONSTRAINT preguntas_pkey PRIMARY KEY (id_pregunta)
    );

CREATE TABLE IF NOT EXISTS public.respuestas_detalle
(
    id_detalle serial NOT NULL,
    id_evaluacion integer NOT NULL,
    id_pregunta integer NOT NULL,
    respuesta_dicotomica boolean NOT NULL,
    valor_frecuencia integer,
    CONSTRAINT respuestas_detalle_pkey PRIMARY KEY (id_detalle)
    );

CREATE TABLE IF NOT EXISTS public.usuarios
(
    id_usuario integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre character varying(100) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT usuarios_pkey PRIMARY KEY (id_usuario)
    );

ALTER TABLE IF EXISTS public.evaluaciones
    ADD CONSTRAINT fk_instrumento_evaluacion FOREIGN KEY (id_instrumento)
    REFERENCES public.instrumentos (id_instrumento) MATCH SIMPLE
    ON UPDATE CASCADE
       ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.evaluaciones
    ADD CONSTRAINT fk_paciente_evaluacion FOREIGN KEY (id_paciente)
    REFERENCES public.pacientes (id_paciente) MATCH SIMPLE
    ON UPDATE CASCADE
       ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.evaluaciones
    ADD CONSTRAINT id_instrumento FOREIGN KEY (id_instrumento)
    REFERENCES public.instrumentos (id_instrumento) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.evaluaciones
    ADD CONSTRAINT id_paciente FOREIGN KEY (id_paciente)
    REFERENCES public.pacientes (id_paciente) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.pacientes
    ADD CONSTRAINT fk_usuario_paciente FOREIGN KEY (id_usuario)
    REFERENCES public.usuarios (id_usuario) MATCH SIMPLE
    ON UPDATE CASCADE
       ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.pacientes
    ADD CONSTRAINT id_usuario FOREIGN KEY (id_usuario)
    REFERENCES public.usuarios (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.preguntas
    ADD CONSTRAINT fk_instrumento_pregunta FOREIGN KEY (id_instrumento)
    REFERENCES public.instrumentos (id_instrumento) MATCH SIMPLE
    ON UPDATE CASCADE
       ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.respuestas_detalle
    ADD CONSTRAINT fk_evaluacion_detalle FOREIGN KEY (id_evaluacion)
    REFERENCES public.evaluaciones (id_evaluacion) MATCH SIMPLE
    ON UPDATE CASCADE
       ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.respuestas_detalle
    ADD CONSTRAINT fk_pregunta_detalle FOREIGN KEY (id_pregunta)
    REFERENCES public.preguntas (id_pregunta) MATCH SIMPLE
    ON UPDATE CASCADE
       ON DELETE CASCADE;

END;